version: "3.8"

services:
  chicwordle:
    image: chicwordle
    build:
      context: .
      dockerfile: ./Dockerfile
      ports:
        - 1985:1985
      volumes:
        - chicwordle_data:/app/data
      environment:
        - APP_DBPATH=/app/data/chicwordle.db
volumes:
  chicwordle_data

